# Generated by Django 2.0.1 on 2018-03-12 20:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'action")),
                ('duration', models.DurationField(default=datetime.timedelta(0), verbose_name='Temps nécessaire par m²')),
                ('is_initial', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='COWithDate',
            fields=[
                ('culturaloperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vegetables_library.CulturalOperation')),
                ('absoluteDate', models.DateField(verbose_name="Date d'échéance")),
            ],
            bases=('vegetables_library.culturaloperation',),
        ),
        migrations.CreateModel(
            name='COWithOffset',
            fields=[
                ('culturaloperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vegetables_library.CulturalOperation')),
                ('offset_in_days', models.IntegerField(verbose_name='Délai en jours')),
            ],
            bases=('vegetables_library.culturaloperation',),
        ),
        migrations.AddField(
            model_name='culturaloperation',
            name='vegetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vegetables_library.Vegetable', verbose_name='Légume concerné'),
        ),
        migrations.AddField(
            model_name='cowithoffset',
            name='previous_operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vegetables_library.CulturalOperation', verbose_name='Opération précédente'),
        ),
    ]
