# Generated by Django 2.0.1 on 2018-04-23 19:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'action")),
                ('duration', models.DurationField(default=datetime.timedelta(0), verbose_name='Temps nécessaire par m²')),
            ],
        ),
        migrations.CreateModel(
            name='GroundSeeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seeding_start', models.DateField()),
                ('seeding_end', models.DateField()),
                ('harvest_start', models.DateField()),
                ('harvest_end', models.DateField()),
                ('cycle_duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OutOfCupSeeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seeding_start', models.DateField()),
                ('seeding_end', models.DateField()),
                ('transplant_start', models.DateField()),
                ('harvest_start', models.DateField()),
                ('harvest_end', models.DateField()),
                ('ground_cycle_duration', models.IntegerField()),
                ('pots_cycle_duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('french_name', models.CharField(max_length=100)),
                ('latin_name', models.CharField(blank=True, max_length=100, null=True)),
                ('family', models.CharField(choices=[('Aizoacées', 'Aizoacées'), ('Amaranthacées', 'Amaranthacées'), ('Amaryllidacées', 'Amaryllidacées'), ('Apiacées', 'Apiacées'), ('Astéracées', 'Astéracées'), ('Boraginacées', 'Boraginacées'), ('Brassicacées', 'Brassicacées'), ('Chénopodiacées', 'Chénopodiacées'), ('Cucurbitacées', 'Cucurbitacées'), ('Fabacées', 'Fabacées'), ('Labiées', 'Labiées'), ('Lamiacées', 'Lamiacées'), ('Légumineuses', 'Légumineuses'), ('Liliacées', 'Liliacées'), ('Papilionacées', 'Papilionacées'), ('Poacées', 'Poacées'), ('Polygonacées', 'Polygonacées'), ('Solanacées', 'Solanacées'), ('Valérianacées', 'Valérianacées'), ('autre', 'autre')], default='autre', max_length=100)),
                ('vegetable_type', models.CharField(choices=[('fruit', 'fruit'), ('graine', 'graine'), ('racine', 'racine'), ('feuille', 'feuille'), ('autre', 'autre')], default='autre', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('french_name', models.CharField(max_length=100)),
                ('latin_name', models.CharField(blank=True, max_length=100, null=True)),
                ('open_ground_seeding', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vegetables_library.GroundSeeding')),
                ('out_of_cup_seeding', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vegetables_library.OutOfCupSeeding')),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vegetables_library.Species')),
            ],
        ),
        migrations.CreateModel(
            name='COWithDate',
            fields=[
                ('culturaloperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vegetables_library.CulturalOperation')),
                ('absoluteDate', models.DateField(verbose_name="Date d'échéance")),
            ],
            bases=('vegetables_library.culturaloperation',),
        ),
        migrations.CreateModel(
            name='COWithOffset',
            fields=[
                ('culturaloperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vegetables_library.CulturalOperation')),
                ('offset_in_days', models.IntegerField(verbose_name='Délai en jours')),
            ],
            bases=('vegetables_library.culturaloperation',),
        ),
        migrations.AddField(
            model_name='culturaloperation',
            name='vegetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vegetables_library.Variety', verbose_name='Légume concerné'),
        ),
        migrations.AlterUniqueTogether(
            name='variety',
            unique_together={('french_name', 'latin_name')},
        ),
        migrations.AddField(
            model_name='cowithoffset',
            name='previous_operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vegetables_library.CulturalOperation', verbose_name='Opération précédente'),
        ),
    ]
