# Generated by Django 2.0.1 on 2018-04-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetables_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outofcupseeding',
            name='transplant_end',
            field=models.DateField(default='2018-04-03'),
            preserve_default=False,
        ),
    ]
