# Generated by Django 2.0.1 on 2018-04-24 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vegetables_library', '0002_outofcupseeding_transplant_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='variety',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outofcupseeding',
            name='pots_cycle_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outofcupseeding',
            name='transplant_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outofcupseeding',
            name='transplant_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variety',
            name='out_of_cup_seeding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vegetables_library.OutOfCupSeeding'),
        ),
        migrations.AlterUniqueTogether(
            name='variety',
            unique_together={('french_name', 'species')},
        ),
    ]
