# Generated by Django 2.0.1 on 2018-04-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetables_library', '0003_remove_culturaloperation_is_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetable',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='vegetable',
            unique_together={('name', 'variety')},
        ),
    ]
