# Generated by Django 2.0.1 on 2018-03-01 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postponement', models.IntegerField(default=0)),
                ('execution_date', models.DateField(null=True)),
                ('duration', models.DurationField(null=True)),
                ('done', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CultivatedArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CulturalOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'action")),
                ('duration', models.DurationField(verbose_name='Temps nécessaire par m²')),
                ('is_initial', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du jardin')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('label', models.CharField(max_length=100)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Garden', unique_for_date=models.DateField())),
            ],
        ),
        migrations.CreateModel(
            name='Surface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('surface_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='planner.Surface')),
                ('area_surface', models.IntegerField()),
            ],
            bases=('planner.surface',),
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('surface_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='planner.Surface')),
                ('name', models.CharField(max_length=100)),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
            ],
            bases=('planner.surface',),
        ),
        migrations.CreateModel(
            name='COWithDate',
            fields=[
                ('culturaloperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='planner.CulturalOperation')),
                ('absoluteDate', models.DateField(verbose_name="Date d'échéance")),
            ],
            bases=('planner.culturaloperation',),
        ),
        migrations.CreateModel(
            name='COWithOffset',
            fields=[
                ('culturaloperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='planner.CulturalOperation')),
                ('offset_in_days', models.IntegerField(verbose_name='Délai en jours')),
            ],
            bases=('planner.culturaloperation',),
        ),
        migrations.AddField(
            model_name='surface',
            name='garden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Garden'),
        ),
        migrations.AddField(
            model_name='culturaloperation',
            name='vegetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Vegetable', verbose_name='Légume concerné'),
        ),
        migrations.AddField(
            model_name='cultivatedarea',
            name='production_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.ProductionPeriod'),
        ),
        migrations.AddField(
            model_name='cultivatedarea',
            name='surface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Surface'),
        ),
        migrations.AddField(
            model_name='cultivatedarea',
            name='vegetable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.Vegetable'),
        ),
        migrations.AddField(
            model_name='alerts',
            name='area_concerned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.CultivatedArea'),
        ),
        migrations.AddField(
            model_name='alerts',
            name='executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alerts',
            name='original_cultural_operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.CulturalOperation'),
        ),
        migrations.AddField(
            model_name='cowithoffset',
            name='previous_operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planner.CulturalOperation', verbose_name='Opération précédente'),
        ),
    ]
