# Generated by Django 2.0.1 on 2018-03-16 14:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CultivatedArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CulturalOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'action")),
                ('duration', models.DurationField(default=datetime.timedelta(0), verbose_name='Temps nécessaire par m²')),
                ('is_initial', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ForthcomingOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postponement', models.IntegerField(default=0)),
                ('execution_date', models.DateField(null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('area_concerned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.CultivatedArea')),
            ],
        ),
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du jardin')),
                ('notification_delay', models.IntegerField(default=5)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GardenDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('garden', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='planner.Garden')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductionPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('label', models.CharField(max_length=100)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Garden', unique_for_date=models.DateField())),
            ],
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('variety', models.CharField(blank=True, max_length=100, null=True)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Garden')),
            ],
        ),
        migrations.CreateModel(
            name='COWithDate',
            fields=[
                ('culturaloperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='planner.CulturalOperation')),
                ('absoluteDate', models.DateField(verbose_name="Date d'échéance")),
            ],
            bases=('planner.culturaloperation',),
        ),
        migrations.CreateModel(
            name='COWithOffset',
            fields=[
                ('culturaloperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='planner.CulturalOperation')),
                ('offset_in_days', models.IntegerField(verbose_name='Délai en jours')),
            ],
            bases=('planner.culturaloperation',),
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('historyitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='planner.HistoryItem')),
                ('description', models.TextField()),
            ],
            bases=('planner.historyitem',),
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('historyitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='planner.HistoryItem')),
                ('name', models.CharField(max_length=100)),
                ('note', models.TextField(null=True)),
                ('duration', models.DurationField(null=True)),
                ('is_deletion', models.BooleanField(default=False)),
            ],
            bases=('planner.historyitem',),
        ),
        migrations.AddField(
            model_name='historyitem',
            name='area_concerned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.CultivatedArea'),
        ),
        migrations.AddField(
            model_name='historyitem',
            name='executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historyitem',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.History'),
        ),
        migrations.AddField(
            model_name='history',
            name='production_period',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planner.ProductionPeriod'),
        ),
        migrations.AddField(
            model_name='forthcomingoperation',
            name='original_cultural_operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.CulturalOperation'),
        ),
        migrations.AddField(
            model_name='culturaloperation',
            name='vegetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Vegetable', verbose_name='Légume concerné'),
        ),
        migrations.AddField(
            model_name='cultivatedarea',
            name='production_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.ProductionPeriod'),
        ),
        migrations.AddField(
            model_name='cultivatedarea',
            name='surface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Bed'),
        ),
        migrations.AddField(
            model_name='cultivatedarea',
            name='vegetable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.Vegetable'),
        ),
        migrations.AddField(
            model_name='bed',
            name='garden',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='planner.Garden'),
        ),
        migrations.AddField(
            model_name='operation',
            name='original_alert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.ForthcomingOperation'),
        ),
        migrations.AddField(
            model_name='cowithoffset',
            name='previous_operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planner.CulturalOperation', verbose_name='Opération précédente'),
        ),
    ]
