# Generated by Django 2.0.1 on 2018-02-08 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionperiod',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='productionperiod',
            name='garden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Garden', unique_for_date=models.DateField()),
        ),
    ]
