# Generated by Django 2.0.1 on 2018-03-16 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='garden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Garden'),
        ),
        migrations.AlterField(
            model_name='gardendetails',
            name='garden',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planner.Garden'),
        ),
    ]
