# Generated by Django 2.0.1 on 2018-01-29 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seeding_start', models.DateField()),
                ('seeding_end', models.DateField()),
                ('harvest_start', models.DateField()),
                ('harvest_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bed',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Bed'),
        ),
        migrations.AddField(
            model_name='event',
            name='vegetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Vegetable'),
        ),
    ]
