# Generated by Django 2.0.1 on 2018-02-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegetable',
            name='initial_co',
        ),
        migrations.AddField(
            model_name='culturaloperation',
            name='is_initial',
            field=models.BooleanField(default=False),
        ),
    ]
