# Generated by Django 2.0.1 on 2018-02-20 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_auto_20180216_1514'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='COperationHistory',
            new_name='CulturalOperationHistory',
        ),
    ]
