# Generated by Django 2.0.1 on 2018-02-14 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_auto_20180208_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='CultivatedArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.ProductionPeriod')),
            ],
        ),
        migrations.RenameModel(
            old_name='CompletedOperation',
            new_name='COperationHistory',
        ),
        migrations.RemoveField(
            model_name='surface',
            name='production_period',
        ),
        migrations.RemoveField(
            model_name='surface',
            name='vegetable',
        ),
        migrations.AlterField(
            model_name='garden',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom du jardin'),
        ),
        migrations.AddField(
            model_name='cultivatedarea',
            name='surface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Surface'),
        ),
        migrations.AddField(
            model_name='cultivatedarea',
            name='vegetable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.Vegetable'),
        ),
    ]
