# Generated by Django 2.0.1 on 2018-02-23 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20180220_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postponement', models.IntegerField(default=0)),
                ('execution_date', models.DateField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='cultivatedarea',
            name='label',
            field=models.TextField(default='label'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cowithdate',
            name='absoluteDate',
            field=models.DateField(verbose_name="Date d'échéance"),
        ),
        migrations.AlterField(
            model_name='cowithoffset',
            name='offset_in_days',
            field=models.IntegerField(verbose_name='Délai en jours'),
        ),
        migrations.AlterField(
            model_name='cowithoffset',
            name='previous_operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planner.CulturalOperation', verbose_name='Opération précédente'),
        ),
        migrations.AlterField(
            model_name='culturaloperation',
            name='duration',
            field=models.IntegerField(verbose_name='Temps nécessaire par m²'),
        ),
        migrations.AlterField(
            model_name='culturaloperation',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Nom de l'action"),
        ),
        migrations.AlterField(
            model_name='culturaloperation',
            name='vegetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Vegetable', verbose_name='Légume concerné'),
        ),
        migrations.AddField(
            model_name='alerts',
            name='area_concerned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.CultivatedArea'),
        ),
        migrations.AddField(
            model_name='alerts',
            name='original_cultural_operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.CulturalOperation'),
        ),
    ]
