# Generated by Django 2.0.1 on 2018-03-20 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_remove_culturaloperation_is_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gardendetails',
            name='garden',
        ),
        migrations.AddField(
            model_name='garden',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='garden',
            name='culture_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='garden',
            name='soil_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cultivatedarea',
            name='vegetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.Vegetable'),
        ),
        migrations.AlterField(
            model_name='forthcomingoperation',
            name='execution_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historyitem',
            name='area_concerned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.CultivatedArea'),
        ),
        migrations.AlterField(
            model_name='historyitem',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operation',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='operation',
            name='original_alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.ForthcomingOperation'),
        ),
        migrations.AlterField(
            model_name='productionperiod',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vegetable',
            name='variety',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='GardenDetails',
        ),
    ]
