# Generated by Django 2.0.1 on 2018-03-09 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0003_garden_notification_delay'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForthcomingOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postponement', models.IntegerField(default=0)),
                ('execution_date', models.DateField(null=True)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.ProductionPeriod')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='alerts',
            name='area_concerned',
        ),
        migrations.RemoveField(
            model_name='alerts',
            name='executor',
        ),
        migrations.RemoveField(
            model_name='alerts',
            name='original_cultural_operation',
        ),
        migrations.AddField(
            model_name='cultivatedarea',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('historyitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='planner.HistoryItem')),
                ('description', models.TextField()),
                ('bed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.Surface')),
            ],
            bases=('planner.historyitem',),
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('historyitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='planner.HistoryItem')),
                ('name', models.TextField(max_length=100)),
                ('note', models.TextField(null=True)),
                ('duration', models.DurationField(null=True)),
                ('is_deletion', models.BooleanField(default=False)),
                ('bed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.Surface')),
            ],
            bases=('planner.historyitem',),
        ),
        migrations.DeleteModel(
            name='Alerts',
        ),
        migrations.AddField(
            model_name='historyitem',
            name='executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historyitem',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.History'),
        ),
        migrations.AddField(
            model_name='historyitem',
            name='vegetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Vegetable'),
        ),
        migrations.AddField(
            model_name='forthcomingoperation',
            name='area_concerned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.CultivatedArea'),
        ),
        migrations.AddField(
            model_name='forthcomingoperation',
            name='original_cultural_operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.CulturalOperation'),
        ),
    ]
