# Generated by Django 2.0.1 on 2018-03-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_auto_20180320_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bed',
            name='culture_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bed',
            name='exposition',
            field=models.CharField(choices=[('N', 'Nord'), ('S', 'Sud'), ('O', 'Ouest'), ('E', 'Est'), ('NE', 'Nord-Est'), ('SE', 'Sud-Est'), ('SO', 'Sud-Ouest'), ('NO', 'Nord-Ouest')], default='N', max_length=2),
        ),
        migrations.AddField(
            model_name='bed',
            name='soil_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
