# Generated by Django 2.0.1 on 2018-02-23 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_auto_20180223_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culturaloperationhistory',
            name='original_C_Operation',
        ),
        migrations.RemoveField(
            model_name='culturaloperationhistory',
            name='production_period',
        ),
        migrations.DeleteModel(
            name='CulturalOperationHistory',
        ),
    ]
