# Generated by Django 2.0.1 on 2018-03-09 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_auto_20180309_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='production_period',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planner.ProductionPeriod'),
        ),
    ]
