# Generated by Django 2.0.1 on 2018-03-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_auto_20180320_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='culture_type',
        ),
        migrations.AlterField(
            model_name='garden',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Description libre du jardin'),
        ),
        migrations.AlterField(
            model_name='garden',
            name='culture_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name="Type d'agriculture pratiquée sur ce jardin"),
        ),
        migrations.AlterField(
            model_name='garden',
            name='soil_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Type de sol'),
        ),
    ]
