# Generated by Django 2.0.1 on 2018-02-27 16:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0005_auto_20180223_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='user',
            field=models.ManyToManyField(related_name='garden_followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
