# Generated by Django 2.0.1 on 2018-03-09 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_auto_20180309_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='original_alert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.ForthcomingOperation'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
