# Generated by Django 2.0.1 on 2018-03-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_auto_20180320_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='reference_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
