# Generated by Django 2.0.1 on 2018-03-30 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_garden_reference_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('historyitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='planner.HistoryItem')),
                ('kg_produced', models.IntegerField(blank=True, default=0)),
                ('total_selling_price', models.IntegerField(blank=True, default=0)),
            ],
            bases=('planner.historyitem',),
        ),
    ]
