# Generated by Django 2.0.1 on 2018-03-12 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_auto_20180309_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetable',
            name='garden',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='planner.Garden'),
        ),
    ]
