# Generated by Django 2.0.1 on 2018-02-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_auto_20180227_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
