# Generated by Django 2.0.1 on 2018-03-30 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_auto_20180330_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivatedarea',
            name='harvest_details',
        ),
        migrations.AddField(
            model_name='harvestdetails',
            name='area_concerned',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='planner.CultivatedArea'),
            preserve_default=False,
        ),
    ]
