# Generated by Django 2.0.1 on 2018-03-30 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0010_auto_20180330_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvestdetails',
            name='area_concerned',
        ),
        migrations.RemoveField(
            model_name='harvestdetails',
            name='executor',
        ),
        migrations.AddField(
            model_name='cultivatedarea',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cultivatedarea',
            name='harvest_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cultivatedarea',
            name='kg_produced',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='cultivatedarea',
            name='total_selling_price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='HarvestDetails',
        ),
    ]
