# Generated by Django 2.0.1 on 2018-03-30 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_auto_20180330_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivatedarea',
            name='production_period',
        ),
        migrations.RemoveField(
            model_name='history',
            name='production_period',
        ),
        migrations.AddField(
            model_name='cultivatedarea',
            name='garden',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='planner.Garden'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='garden',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='planner.Garden'),
            preserve_default=False,
        ),
    ]
