# Generated by Django 2.0.1 on 2018-03-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_auto_20180330_1606'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductionPeriod',
        ),
    ]
