# Generated by Django 2.0.1 on 2018-04-07 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_auto_20180330_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='activity_data_available_for_research',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='garden',
            name='details_available_for_research',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='garden',
            name='postal_code',
            field=models.IntegerField(default=1000, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1000)]),
        ),
    ]
