# Generated by Django 2.0.1 on 2018-04-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0016_auto_20180411_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetable',
            name='extern_id',
            field=models.IntegerField(null=True),
        ),
    ]
