# Generated by Django 2.0.1 on 2018-04-24 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0017_vegetable_extern_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Commentaire éventuel'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='exposition',
            field=models.CharField(choices=[('N', 'Nord'), ('S', 'Sud'), ('O', 'Ouest'), ('E', 'Est'), ('NE', 'Nord-Est'), ('SE', 'Sud-Est'), ('SO', 'Sud-Ouest'), ('NO', 'Nord-Ouest')], default='N', max_length=2, verbose_name='Exposition'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='length',
            field=models.IntegerField(verbose_name='Longueur (cm)'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='soil_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Type de sol'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='width',
            field=models.IntegerField(verbose_name='Largeur (cm)'),
        ),
        migrations.AlterField(
            model_name='cultivatedarea',
            name='harvest_date',
            field=models.DateField(null=True, verbose_name='Date de récolte'),
        ),
        migrations.AlterField(
            model_name='cultivatedarea',
            name='kg_produced',
            field=models.IntegerField(blank=True, default=0, verbose_name='Quantité récoltée (kg)'),
        ),
        migrations.AlterField(
            model_name='cultivatedarea',
            name='label',
            field=models.TextField(verbose_name='Label de la culture'),
        ),
        migrations.AlterField(
            model_name='cultivatedarea',
            name='surface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Bed', verbose_name='Planche'),
        ),
        migrations.AlterField(
            model_name='cultivatedarea',
            name='total_selling_price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Prix de vente total (€)'),
        ),
        migrations.AlterField(
            model_name='cultivatedarea',
            name='vegetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.Vegetable', verbose_name='Légume cultivé'),
        ),
        migrations.AlterField(
            model_name='historyitem',
            name='area_concerned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.CultivatedArea', verbose_name='Culture concernée'),
        ),
        migrations.AlterField(
            model_name='historyitem',
            name='execution_date',
            field=models.DateField(verbose_name="Date d'exécution"),
        ),
        migrations.AlterField(
            model_name='observation',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Durée'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Nom de l'opération"),
        ),
        migrations.AlterField(
            model_name='vegetable',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='vegetable',
            name='variety',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Variété'),
        ),
    ]
