# Generated by Django 2.0.1 on 2018-05-10 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0018_auto_20180424_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='x',
            field=models.IntegerField(default=0, verbose_name='Coodinate X of upper-left corner of the rectangle'),
        ),
        migrations.AddField(
            model_name='bed',
            name='y',
            field=models.IntegerField(default=0, verbose_name='Coordinate Y of upper-left corner of the rectangle'),
        ),
        migrations.AlterField(
            model_name='garden',
            name='postal_code',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1000)], verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='vegetable',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Espèce'),
        ),
    ]
