# Generated by Django 2.0.1 on 2018-05-30 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0020_auto_20180528_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiocideUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_name', models.CharField(max_length=200, verbose_name='Nom commercial du produit')),
                ('usage_date', models.DateField(verbose_name="Date d'application")),
                ('dose_used', models.IntegerField(verbose_name='Dose utilisée')),
                ('unity', models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('l', 'l')], max_length=2, verbose_name='Unité')),
                ('gear_treated', models.CharField(max_length=200, verbose_name='Equipement traité')),
            ],
        ),
        migrations.CreateModel(
            name='IncomingPhytosanitaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_name', models.CharField(max_length=200, verbose_name='Nom commercial du produit')),
                ('quantity', models.IntegerField(verbose_name='Quantité')),
                ('unity', models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('l', 'l')], max_length=2, verbose_name='Unité')),
                ('receipt_date', models.DateField(verbose_name='Date de réception')),
                ('supplier', models.CharField(max_length=200, verbose_name="Identification de l'unité fournissant le produit")),
            ],
        ),
        migrations.CreateModel(
            name='PhytosanitaireUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_name', models.CharField(max_length=200, verbose_name='Nom commercial du produit')),
                ('usage_date', models.DateField(verbose_name="Date d'application")),
                ('dose_used', models.IntegerField(verbose_name='Dose utilisée')),
                ('unity', models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('l', 'l')], max_length=2, verbose_name='Unité')),
                ('crop_treated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.CultivatedArea')),
            ],
        ),
        migrations.AlterField(
            model_name='bed',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='parcel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.Parcel', verbose_name='Parcelle'),
        ),
        migrations.AlterField(
            model_name='culturaloperation',
            name='name',
            field=models.CharField(max_length=200, verbose_name="Nom de l'action"),
        ),
        migrations.AlterField(
            model_name='garden',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nom du jardin'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='name',
            field=models.CharField(max_length=200, verbose_name="Nom de l'opération"),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='phytosanitaireusage',
            name='garden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Garden'),
        ),
        migrations.AddField(
            model_name='incomingphytosanitaire',
            name='garden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Garden'),
        ),
        migrations.AddField(
            model_name='biocideusage',
            name='garden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Garden'),
        ),
    ]
