# Generated by Django 2.0.1 on 2018-05-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0022_auto_20180530_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingphytosanitaire',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=13, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='phytosanitaireusage',
            name='dose_used',
            field=models.DecimalField(decimal_places=3, max_digits=13, verbose_name='Dose utilisée'),
        ),
    ]
